name: Sync Pi Node

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sync Public Node
        run: |
          ssh -o StrictHostKeyChecking=no moghimi@10.0.0.111 "
            cd ~/kmtos-public &&
            git pull
          "

